
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.BlockInformation.EndProcessing(System.Object)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.BlockInformation.StartProcessing(System.Object)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.DraggingHelper.FindAncestor``1(System.Windows.DependencyObject)~``0")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.DraggingHelper.OnMouseLeftButtonUp(System.Object,System.Windows.Input.MouseButtonEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.DraggingHelper.OnMouseMove(System.Object,System.Windows.Input.MouseEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.Hooks.LinkHook`1.ConsumeMessage(System.Threading.Tasks.Dataflow.DataflowMessageHeader,System.Threading.Tasks.Dataflow.ITargetBlock{`0},System.Boolean@)~`0")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.Hooks.LinkHook`1.OfferMessage(System.Threading.Tasks.Dataflow.DataflowMessageHeader,`0,System.Threading.Tasks.Dataflow.ISourceBlock{`0},System.Boolean)~System.Threading.Tasks.Dataflow.DataflowMessageStatus")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.Hooks.PropogateHook`2.OfferMessage(System.Threading.Tasks.Dataflow.DataflowMessageHeader,`0,System.Threading.Tasks.Dataflow.ISourceBlock{`0},System.Boolean)~System.Threading.Tasks.Dataflow.DataflowMessageStatus")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.Hooks.SourceHook`1.ConsumeMessage(System.Threading.Tasks.Dataflow.DataflowMessageHeader,System.Threading.Tasks.Dataflow.ITargetBlock{`0},System.Boolean@)~`0")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.Hooks.TargetHook`1.OfferMessage(System.Threading.Tasks.Dataflow.DataflowMessageHeader,`0,System.Threading.Tasks.Dataflow.ISourceBlock{`0},System.Boolean)~System.Threading.Tasks.Dataflow.DataflowMessageStatus")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.ItemsTemplateSelector.SelectTemplate(System.Object,System.Windows.DependencyObject)~System.Windows.DataTemplate")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.ReflectActionBlock`1.#ctor(System.Threading.Tasks.Dataflow.IDataflowBlock,Bnaya.Samples.IBlockInitializer)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.ReflectBlock.#ctor(System.Threading.Tasks.Dataflow.IDataflowBlock,Bnaya.Samples.IBlockInitializer)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.ReflectBlockExtensions.GetCurrentDegreeOfParallelism(System.Object)~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.ReflectBlockExtensions.GetDataflowBlockOptions(System.Object)~System.Threading.Tasks.Dataflow.ExecutionDataflowBlockOptions")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.ReflectBlockExtensions.GetIsCompleted(System.Object)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.ReflectBlockExtensions.GetIsDecliningPermanently(System.Object)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.ReflectBlockExtensions.GetProsponedQueue(System.Object)~System.Collections.Generic.IEnumerable{Bnaya.Samples.PostponedMessage}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.ReflectBlockExtensions.GetQueue(System.Object,System.String)~System.Collections.Generic.IEnumerable{System.String}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.ReflectBufferBlock`1.SetBoundingState(System.Threading.Tasks.Dataflow.IDataflowBlock,Bnaya.Samples.IBlockInitializer)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.ReflectSourceBlock`1.#ctor(System.Threading.Tasks.Dataflow.ISourceBlock{`0},Bnaya.Samples.IBlockInitializer)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.ReflectSourceBlock`1.InitProperties(System.Threading.Tasks.Dataflow.ISourceBlock{`0},Bnaya.Samples.IBlockInitializer)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.ReflectSourceBlock`1.IsLinked(Bnaya.Samples.LinkToInformation)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.ReflectSourceBlock`1.SetNextMessageIdProperty(System.Object,Bnaya.Samples.IBlockInitializer)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.ReflectSourceBlock`1.SetTaskForOutputProcessing(Bnaya.Samples.IBlockInitializer)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:Bnaya.Samples.ReflectTransformBlock`2.#ctor(System.Threading.Tasks.Dataflow.TransformBlock{`0,`1},Bnaya.Samples.IBlockInitializer)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~P:Bnaya.Samples.ReflectSourceBlock`1.OutputQueue")]

